### create user
POST http://127.0.0.1:8080/user
Content-Type: application/json

{
  "first_name":"zha",
  "last_name":"b1",
  "email":"12@121.com",
  "password":"asdasdasd"
}

> {%    client.log(JSON.stringify(response.body)) %}

### get all  users
GET http://127.0.0.1:8080/users

> {%    client.log(JSON.stringify(response.body)) %}

### get users by id

GET http://127.0.0.1:8080/users/1

> {%    client.log(JSON.stringify(response.body)) %}


### login by email and password

POST http://127.0.0.1:8080/login

{
    "email":"12@12.com",
    "password":"asdasdasd"
}

> {%
 client.log(JSON.stringify(response.body))
 client.global.set("auth_token",response.body.access_token)
 %}
